version: 1 # [required]
root: . # [required] the root folder where the project is
main_path: /cmd/goverage/main.go
build_args: -c ./tests/crud/coverage.txt -p ./tests/crud -o ./tmp/coverage.html
ignore_folder: tmp
valid_ext: .go, .tpl, .tmp, .css, .html
